[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "postgresql", "openssl"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "cd odoo-18.0+e.20250521 && python -m odoo --config=/app/odoo.conf --db-filter=^%d$ --without-demo=all --data-dir=/app/filestore" 